const ocupaciones = [{codigo: "9629", ocupacion: "Ocupaciones elementales no clasificadas bajo otros epígrafes"},
{codigo: "0110", ocupacion: "Oficiales de las fuerzas armadas"},
{codigo: "0210", ocupacion: "Suboficiales de las fuerzas armadas"},
{codigo: "0310", ocupacion: "Otros miembros de las fuerzas armadas"},
{codigo: "1111", ocupacion: "Miembros del poder legislativo"},
{codigo: "1112", ocupacion: "Personal directivo de la administración pública"},
{codigo: "1113", ocupacion: "Jefes de pequeñas poblaciones"},
{codigo: "1114", ocupacion: "Dirigentes de organizaciones que presentan un interés especial"},
{codigo: "1120", ocupacion: "Directores generales y gerentes generales"},
{codigo: "1211", ocupacion: "Directores financieros"},
{codigo: "1212", ocupacion: "Directores de recursos humanos"},
{codigo: "1213", ocupacion: "Directores de políticas y planificación"},
{codigo: "1219", ocupacion: "Directores de administración y servicios no clasificados bajo otros epígrafes"},
{codigo: "1221", ocupacion: "Directores de ventas y comercialización"},
{codigo: "1222", ocupacion: "Directores de publicidad y relaciones públicas"},
{codigo: "1223", ocupacion: "Directores de investigación y desarrollo"},
{codigo: "1311", ocupacion: "Directores de producción agropecuaria y silvicultura"},
{codigo: "1312", ocupacion: "Directores de producción de piscicultura y pesca"},
{codigo: "1321", ocupacion: "Directores de industrias manufactureras"},
{codigo: "1322", ocupacion: "Directores de explotaciones de minería"},
{codigo: "1323", ocupacion: "Directores de empresas de construcción"},
{codigo: "1324", ocupacion: "Directores de empresas de abastecimiento, distribución y afines"},
{codigo: "1330", ocupacion: "Directores de servicios de tecnología de la información y las comunicaciones"},
{codigo: "1341", ocupacion: "Directores de servicios de cuidados infantiles"},
{codigo: "1342", ocupacion: "Directores de servicios de salud"},
{codigo: "1343", ocupacion: "Directores de servicios de cuidado de las personas de edad"},
{codigo: "1344", ocupacion: "Directores  de servicios de bienestar social"},
{codigo: "1345", ocupacion: "Directores de servicios de educación"},
{codigo: "1346", ocupacion: "Gerentes de sucursales de bancos, de servicios financieros y de seguros"},
{codigo: "1349", ocupacion: "Directores y gerentes de servicios profesionales no clasificados bajo otros epígrafes"},
{codigo: "1411", ocupacion: "Gerentes de hoteles"},
{codigo: "1412", ocupacion: "Gerentes de restaurantes"},
{codigo: "1420", ocupacion: "Gerentes de comercios al por mayor y al por menor"},
{codigo: "1431", ocupacion: "Gerentes de centros deportivos, de esparcimiento y culturales"},
{codigo: "1439", ocupacion: "Gerentes de servicios no clasificados bajo otros epígrafes"},
{codigo: "2111", ocupacion: "Físicos y astrónomos"},
{codigo: "2112", ocupacion: "Meteorólogos"},
{codigo: "2113", ocupacion: "Químicos"},
{codigo: "2114", ocupacion: "Geólogos y geofísicos"},
{codigo: "2120", ocupacion: "Matemáticos, actuarios y estadísticos"},
{codigo: "2131", ocupacion: "Biólogos, botánicos, zoólogos y afines"},
{codigo: "2132", ocupacion: "Agrónomos y afines"},
{codigo: "2133", ocupacion: "Profesionales de la protección medioambiental"},
{codigo: "2141", ocupacion: "Ingenieros industriales y de producción"},
{codigo: "2142", ocupacion: "Ingenieros civiles"},
{codigo: "2143", ocupacion: "Ingenieros medioambientales"},
{codigo: "2144", ocupacion: "Ingenieros mecánicos"},
{codigo: "2145", ocupacion: "Ingenieros químicos"},
{codigo: "2146", ocupacion: "Ingenieros de minas, metalúrgicos y afines"},
{codigo: "2149", ocupacion: "Ingenieros no clasificados bajo otros epígrafes"},
{codigo: "2151", ocupacion: "Ingenieros electricistas"},
{codigo: "2152", ocupacion: "Ingenieros electrónicos"},
{codigo: "2153", ocupacion: "Ingenieros en telecomunicaciones"},
{codigo: "2161", ocupacion: "Arquitectos"},
{codigo: "2162", ocupacion: "Arquitectos paisajistas"},
{codigo: "2163", ocupacion: "Diseñadores de productos y de prendas"},
{codigo: "2164", ocupacion: "Urbanistas e ingenieros de tránsito"},
{codigo: "2165", ocupacion: "Cartógrafos y agrimensores"},
{codigo: "2166", ocupacion: "Diseñadores gráficos y multimedia"},
{codigo: "2211", ocupacion: "Médicos generales"},
{codigo: "2212", ocupacion: "Médicos especialistas "},
{codigo: "2221", ocupacion: "Profesionales de enfermería"},
{codigo: "2222", ocupacion: "Profesionales de partería"},
{codigo: "2230", ocupacion: "Profesionales de medicina tradicional y alternativa"},
{codigo: "2240", ocupacion: "Practicantes paramédicos"},
{codigo: "2250", ocupacion: "Veterinarios"},
{codigo: "2261", ocupacion: "Dentistas"},
{codigo: "2262", ocupacion: "Farmacéuticos"},
{codigo: "2263", ocupacion: "Profesionales de la salud y la higiene laboral y ambiental"},
{codigo: "2264", ocupacion: "Fisioterapeutas "},
{codigo: "2265", ocupacion: "Dietistas y nutricionistas"},
{codigo: "2266", ocupacion: "Audiólogos y logopedas"},
{codigo: "2267", ocupacion: "Optometristas"},
{codigo: "2269", ocupacion: "Profesionales de la salud no clasificados bajo otros epígrafes"},
{codigo: "2310", ocupacion: "Profesores de universidades y de la enseñanza superior"},
{codigo: "2320", ocupacion: "Profesores de formación profesional"},
{codigo: "2330", ocupacion: "Profesores de enseñanza secundaria"},
{codigo: "2341", ocupacion: "Maestros de enseñanza primaria"},
{codigo: "2342", ocupacion: "Maestros preescolares"},
{codigo: "2351", ocupacion: "Especialistas en métodos pedagógicos"},
{codigo: "2352", ocupacion: "Educadores para necesidades especiales"},
{codigo: "2353", ocupacion: "Otros profesores de idiomas"},
{codigo: "2354", ocupacion: "Otros profesores de música"},
{codigo: "2355", ocupacion: "Otros profesores de artes"},
{codigo: "2356", ocupacion: "Instructores en tecnología de la información"},
{codigo: "2359", ocupacion: "Profesionales de la enseñanza no clasificados bajo otros epígrafes"},
{codigo: "2411", ocupacion: "Contables"},
{codigo: "2412", ocupacion: "Asesores financieros y en inversiones"},
{codigo: "2413", ocupacion: "Analistas financieros"},
{codigo: "2421", ocupacion: "Analistas de gestión y organización"},
{codigo: "2422", ocupacion: "Especialistas en políticas de administración"},
{codigo: "2423", ocupacion: "Especialistas en políticas y servicios de personal y afines"},
{codigo: "2424", ocupacion: "Especialistas en formación del personal"},
{codigo: "2431", ocupacion: "Profesionales de la publicidad y la comercialización"},
{codigo: "2432", ocupacion: "Profesionales de relaciones públicas"},
{codigo: "2433", ocupacion: "Profesionales de ventas técnicas y médicas (excluyendo la TIC)"},
{codigo: "2434", ocupacion: "Profesionales de ventas de tecnología de la información y las comunicaciones"},
{codigo: "2511", ocupacion: "Analistas de sistemas"},
{codigo: "2512", ocupacion: "Desarrolladores de software"},
{codigo: "2513", ocupacion: "Desarrolladores Web y multimedia"},
{codigo: "2514", ocupacion: "Programadores de aplicaciones"},
{codigo: "2519", ocupacion: "Desarrolladores y analistas de software y multimedia y analistas no clasificados bajo otros epígrafes"},
{codigo: "2521", ocupacion: "Diseñadores y administradores de bases de datos"},
{codigo: "2522", ocupacion: "Administradores de sistemas"},
{codigo: "2523", ocupacion: "Profesionales en redes de computadores"},
{codigo: "2529", ocupacion: "Especialistas en bases de datos y en redes de computadores no clasificados bajo otros epígrafes"},
{codigo: "2611", ocupacion: "Abogados"},
{codigo: "2612", ocupacion: "Jueces"},
{codigo: "2619", ocupacion: "Profesionales en derecho no clasificados bajo otros epígrafes"},
{codigo: "2621", ocupacion: "Archivistas y curadores de museos"},
{codigo: "2622", ocupacion: "Bibliotecarios, documentalistas y afines"},
{codigo: "2631", ocupacion: "Economistas"},
{codigo: "2632", ocupacion: "Sociólogos, antropólogos y afines"},
{codigo: "2633", ocupacion: "Filósofos, historiadores y especialistas en ciencias políticas"},
{codigo: "2634", ocupacion: "Psicólogos"},
{codigo: "2635", ocupacion: "Profesionales del trabajo social"},
{codigo: "2636", ocupacion: "Profesionales religiosos"},
{codigo: "2641", ocupacion: "Autores y otros escritores"},
{codigo: "2642", ocupacion: "Periodistas"},
{codigo: "2643", ocupacion: "Traductores, intérpretes y lingüistas"},
{codigo: "2651", ocupacion: "Artistas de artes plásticas"},
{codigo: "2652", ocupacion: "Músicos, cantantes y compositores"},
{codigo: "2653", ocupacion: "Bailarines y coreógrafos"},
{codigo: "2654", ocupacion: "Directores de cine, de teatro y afines"},
{codigo: "2655", ocupacion: "Actores"},
{codigo: "2656", ocupacion: "Locutores de radio, televisión y otros medios de comunicación"},
{codigo: "2659", ocupacion: "Artistas creativos e interpretativos no clasificados bajo otros epígrafes"},
{codigo: "3111", ocupacion: "Técnicos en ciencias físicas y químicas"},
{codigo: "3112", ocupacion: "Técnicos en ingeniería civil"},
{codigo: "3113", ocupacion: "Electrotécnicos"},
{codigo: "3114", ocupacion: "Técnicos en electrónica"},
{codigo: "3115", ocupacion: "Técnicos en ingeniería mecánica"},
{codigo: "3116", ocupacion: "Técnicos en química industrial"},
{codigo: "3117", ocupacion: "Técnicos en ingeniería de minas y metalurgia"},
{codigo: "3118", ocupacion: "Delineantes y dibujantes técnicos"},
{codigo: "3119", ocupacion: "Técnicos en ciencias físicas y en ingeniería no clasificados bajo otros epígrafes"},
{codigo: "3121", ocupacion: "Supervisores en ingeniería de minas"},
{codigo: "3122", ocupacion: "Supervisores de industrias manufactureras"},
{codigo: "3123", ocupacion: "Supervisores de la construcción"},
{codigo: "3131", ocupacion: "Operadores de instalaciones de producción de energía"},
{codigo: "3132", ocupacion: "Operadores de incineradores, instalaciones de tratamiento de agua y afines"},
{codigo: "3133", ocupacion: "Controladores de instalaciones de procesamiento de productos químicos"},
{codigo: "3134", ocupacion: "Operadores de instalaciones de refinación de petróleo y gas natural"},
{codigo: "3135", ocupacion: "Controladores de procesos de producción de metales"},
{codigo: "3139", ocupacion: "Técnicos en control de procesos no clasificados bajo otros epígrafes"},
{codigo: "3141", ocupacion: "Técnicos en ciencias biológicas (excluyendo la medicina)"},
{codigo: "3142", ocupacion: "Técnicos agropecuarios"},
{codigo: "3143", ocupacion: "Técnicos forestales"},
{codigo: "3151", ocupacion: "Oficiales maquinistas en navegación"},
{codigo: "3152", ocupacion: "Capitanes, oficiales de cubierta y prácticos"},
{codigo: "3153", ocupacion: "Pilotos de aviación y afines"},
{codigo: "3154", ocupacion: "Controladores de tráfico aéreo"},
{codigo: "3155", ocupacion: "Técnicos en seguridad aeronáutica"},
{codigo: "3211", ocupacion: "Técnicos en aparatos de diagnóstico y tratamiento médico"},
{codigo: "3212", ocupacion: "Técnicos de laboratorios médicos"},
{codigo: "3213", ocupacion: "Técnicos y asistentes farmacéuticos"},
{codigo: "3214", ocupacion: "Técnicos de prótesis médicas y dentales"},
{codigo: "3221", ocupacion: "Profesionales de nivel medio de enfermería"},
{codigo: "3222", ocupacion: "Profesionales de nivel medio de partería"},
{codigo: "3230", ocupacion: "Profesionales de nivel medio de medicina tradicional y alternativa"},
{codigo: "3240", ocupacion: "Técnicos y asistentes veterinarios"},
{codigo: "3251", ocupacion: "Dentistas auxiliares y ayudantes de odontología"},
{codigo: "3252", ocupacion: "Técnicos en documentación sanitaria"},
{codigo: "3253", ocupacion: "Trabajadores comunitarios de la salud"},
{codigo: "3254", ocupacion: "Técnicos en optometría y ópticos"},
{codigo: "3255", ocupacion: "Técnicos y asistentes fisioterapeutas"},
{codigo: "3256", ocupacion: "Practicantes y asistentes médicos"},
{codigo: "3257", ocupacion: "Inspectores de la salud laboral,  medioambiental y afines"},
{codigo: "3258", ocupacion: "Ayudantes de ambulancias"},
{codigo: "3259", ocupacion: "Profesionales de la salud de nivel medio no clasificados bajo otros epígrafes"},
{codigo: "3311", ocupacion: "Agentes de bolsa, cambio y otros servicios financieros"},
{codigo: "3312", ocupacion: "Oficiales de préstamos y créditos"},
{codigo: "3313", ocupacion: "Tenedores de libros"},
{codigo: "3314", ocupacion: "Profesionales de nivel medio de servicios estadísticos, matemáticos y afines"},
{codigo: "3315", ocupacion: "Tasadores"},
{codigo: "3321", ocupacion: "Agentes de seguros"},
{codigo: "3322", ocupacion: "Representantes comerciales"},
{codigo: "3323", ocupacion: "Agentes de compras"},
{codigo: "3324", ocupacion: "Agentes de compras y consignatarios"},
{codigo: "3331", ocupacion: "Declarantes o gestores de aduana"},
{codigo: "3332", ocupacion: "Organizadores de conferencias y eventos"},
{codigo: "3333", ocupacion: "Agentes de empleo y contratistas de mano de obra"},
{codigo: "3334", ocupacion: "Agentes inmobiliarios"},
{codigo: "3339", ocupacion: "Agentes de servicios comerciales no clasificados bajo otros epígrafes"},
{codigo: "3341", ocupacion: "Supervisores de secretaría"},
{codigo: "3342", ocupacion: "Secretarios jurídicos"},
{codigo: "3343", ocupacion: "Secretarios administrativos y ejecutivos"},
{codigo: "3344", ocupacion: "Secretarios médicos"},
{codigo: "3351", ocupacion: "Agentes de aduana e inspectores de fronteras"},
{codigo: "3352", ocupacion: "Agentes de administración tributaria"},
{codigo: "3353", ocupacion: "Agentes de servicios de seguridad social"},
{codigo: "3354", ocupacion: "Agentes de servicios de expedición de licencias y permisos"},
{codigo: "3355", ocupacion: "Inspectores de policía y detectives"},
{codigo: "3359", ocupacion: "Agentes de la administración pública para la aplicacion de la ley y afines no clasificados bajo otros epígrafes"},
{codigo: "3411", ocupacion: "Profesionales de nivel medio del derecho y servicios legales y afines"},
{codigo: "3412", ocupacion: "Trabajadores y asistentes sociales de nivel medio"},
{codigo: "3413", ocupacion: "Auxiliares laicos de las religiones"},
{codigo: "3421", ocupacion: "Atletas y deportistas"},
{codigo: "3422", ocupacion: "Entrenadores, instructores y árbitros de actividades deportivas"},
{codigo: "3423", ocupacion: "Instructores de educación física y actividades recreativas"},
{codigo: "3431", ocupacion: "Fotógrafos"},
{codigo: "3432", ocupacion: "Diseñadores y decoradores de interior"},
{codigo: "3433", ocupacion: "Técnicos en galerías de arte, museos y bibliotecas"},
{codigo: "3434", ocupacion: "Chefs"},
{codigo: "3435", ocupacion: "Otros profesionales de nivel medio en actividades culturales y artísticas"},
{codigo: "3511", ocupacion: "Técnicos en operaciones de tecnología de la información y las comunicaciones"},
{codigo: "3512", ocupacion: "Técnicos en asistencia al usuario de tecnología de la información y las comunicaciones"},
{codigo: "3513", ocupacion: "Técnicos en redes y sistemas de computadores"},
{codigo: "3514", ocupacion: "Técnicos de la Web"},
{codigo: "3521", ocupacion: "Técnicos de radiodifusión y grabación audio visual"},
{codigo: "3522", ocupacion: "Técnicos de ingeniería de las telecomunicaciones"},
{codigo: "4110", ocupacion: "Oficinistas generales"},
{codigo: "4120", ocupacion: "Secretarios (general)"},
{codigo: "4131", ocupacion: "Operadores de máquinas de procesamiento de texto y mecanógrafos"},
{codigo: "4132", ocupacion: "Grabadores de datos"},
{codigo: "4211", ocupacion: "Cajeros de bancos y afines"},
{codigo: "4212", ocupacion: "Receptores de apuestas y afines"},
{codigo: "4213", ocupacion: "Prestamistas"},
{codigo: "4214", ocupacion: "Cobradores y afines"},
{codigo: "4221", ocupacion: "Empleados de agencias de viajes"},
{codigo: "4222", ocupacion: "Empleados de centros de llamadas"},
{codigo: "4223", ocupacion: "Telefonistas"},
{codigo: "4224", ocupacion: "Recepcionistas de hoteles"},
{codigo: "4225", ocupacion: "Empleados de ventanillas de informaciones"},
{codigo: "4226", ocupacion: "Recepcionistas (general)"},
{codigo: "4227", ocupacion: "Entrevistadores de encuestas y de investigaciones de mercados"},
{codigo: "4229", ocupacion: "Empleados de servicios de información al cliente no clasificados bajo otros epígrafes"},
{codigo: "4311", ocupacion: "Empleados de contabilidad y cálculo de costos"},
{codigo: "4312", ocupacion: "Empleados de servicios estadísticos, financieros y de seguros"},
{codigo: "4313", ocupacion: "Empleados encargados de las nóminas"},
{codigo: "4321", ocupacion: "Empleados de control de abastecimientos e inventario"},
{codigo: "4322", ocupacion: "Empleados de servicios de apoyo a la producción"},
{codigo: "4323", ocupacion: "Empleados de servicios de transporte"},
{codigo: "4411", ocupacion: "Empleados de bibliotecas"},
{codigo: "4412", ocupacion: "Empleados de servicios de correos"},
{codigo: "4413", ocupacion: "Codificadores de datos, correctores de pruebas de imprenta y afines"},
{codigo: "4414", ocupacion: "Escribientes públicos y afines"},
{codigo: "4415", ocupacion: "Empleados de archivos"},
{codigo: "4416", ocupacion: "Empleados del servicio de personal"},
{codigo: "4419", ocupacion: "Personal de apoyo administrativo no clasificado bajo otros epígrafes"},
{codigo: "5111", ocupacion: "Auxiliares de servicio de abordo"},
{codigo: "5112", ocupacion: "Revisores y cobradores de los transportes públicos"},
{codigo: "5113", ocupacion: "Guías de turismo"},
{codigo: "5120", ocupacion: "Cocineros"},
{codigo: "5131", ocupacion: "Camareros de mesas"},
{codigo: "5132", ocupacion: "Camareros de barra"},
{codigo: "5141", ocupacion: "Peluqueros"},
{codigo: "5142", ocupacion: "Especialistas en tratamientos de belleza y afines"},
{codigo: "5151", ocupacion: "Supervisores de mantenimiento y limpieza en oficinas, hoteles y otros establecimientos"},
{codigo: "5152", ocupacion: "Ecónomos y mayordomos domésticos "},
{codigo: "5153", ocupacion: "Conserjes"},
{codigo: "5161", ocupacion: "Astrólogos, adivinadores y afines"},
{codigo: "5162", ocupacion: "Acompañantes y ayudantes de cámara"},
{codigo: "5163", ocupacion: "Personal de pompas fúnebres y embalsamadores"},
{codigo: "5164", ocupacion: "Cuidadores de animales"},
{codigo: "5165", ocupacion: "Instructores de autoescuela"},
{codigo: "5169", ocupacion: "Trabajadores de servicios personales no clasificados bajo otros epígrafes"},
{codigo: "5211", ocupacion: "Vendedores de quioscos y de puestos de mercado"},
{codigo: "5212", ocupacion: "Vendedores ambulantes de productos comestibles"},
{codigo: "5221", ocupacion: "Comerciantes de tiendas"},
{codigo: "5222", ocupacion: "Supervisores de tiendas y almacenes"},
{codigo: "5223", ocupacion: "Asistentes de venta de tiendas y almacenes"},
{codigo: "5230", ocupacion: "Cajeros y expendedores de billetes"},
{codigo: "5241", ocupacion: "Modelos de moda, arte y publicidad"},
{codigo: "5242", ocupacion: "Demostradores de tiendas"},
{codigo: "5243", ocupacion: "Vendedores puerta a puerta"},
{codigo: "5244", ocupacion: "Vendedores por teléfono"},
{codigo: "5245", ocupacion: "Expendedores de gasolineras"},
{codigo: "5246", ocupacion: "Vendedores de comidas al mostrador"},
{codigo: "5249", ocupacion: "Vendedores no clasificados bajo otros epígrafes"},
{codigo: "5311", ocupacion: "Cuidadores de niños"},
{codigo: "5312", ocupacion: "Auxiliares de maestros"},
{codigo: "5321", ocupacion: "Trabajadores de los cuidados personales en instituciones"},
{codigo: "5322", ocupacion: "Trabajadores de los cuidados personales a domicilio"},
{codigo: "5329", ocupacion: "Trabajadores de los cuidados personales en servicios de salud no clasificados bajo otros epígrafes"},
{codigo: "5411", ocupacion: "Bomberos"},
{codigo: "5412", ocupacion: "Policías"},
{codigo: "5413", ocupacion: "Guardianes de prisión"},
{codigo: "5414", ocupacion: "Guardias de protección"},
{codigo: "5419", ocupacion: "Personal de los servicios de protección no clasificados bajo otros epígrafes"},
{codigo: "6111", ocupacion: "Agricultores y trabajadores calificados de cultivos extensivos"},
{codigo: "6112", ocupacion: "Agricultores y trabajadores calificados de plantaciones de árboles y arbustos"},
{codigo: "6113", ocupacion: "Agricultores y trabajadores calificados de huertas, invernaderos, viveros y jardines"},
{codigo: "6114", ocupacion: "Agricultores y trabajadores calificados de cultivos mixtos"},
{codigo: "6121", ocupacion: "Criadores de ganado"},
{codigo: "6122", ocupacion: "Avicultores y trabajadores calificados de la avicultura"},
{codigo: "6123", ocupacion: "Apicultores y sericultores y trabajadores calificados de la apicultura y la sericultura"},
{codigo: "6129", ocupacion: "Criadores y trabajadores pecuarios calificados de la cría de animales no clasificados bajo otros epígrafes"},
{codigo: "6130", ocupacion: "Productores y trabajadores calificados de explotaciones agropecuarias mixtas cuya producción se destina al mercado"},
{codigo: "6210", ocupacion: "Trabajadores forestales calificados y afines"},
{codigo: "6221", ocupacion: "Trabajadores de explotaciones de acuicultura"},
{codigo: "6222", ocupacion: "Pescadores de agua dulce y en aguas costeras"},
{codigo: "6223", ocupacion: "Pescadores de alta mar"},
{codigo: "6224", ocupacion: "Cazadores y tramperos"},
{codigo: "6310", ocupacion: "Trabajadores agrícolas de subsistencia"},
{codigo: "6320", ocupacion: "Trabajadores pecuarios de subsistencia"},
{codigo: "6330", ocupacion: "Trabajadores agropecuarios de subsistencia"},
{codigo: "6340", ocupacion: "Pescadores, cazadores, tramperos y recolectores de subsistencia"},
{codigo: "7111", ocupacion: "Constructores de casas"},
{codigo: "7112", ocupacion: "Albañiles"},
{codigo: "7113", ocupacion: "Mamposteros, tronzadores, labrantes y grabadores de piedra"},
{codigo: "7114", ocupacion: "Operarios en cemento armado, enfoscadores y afines"},
{codigo: "7115", ocupacion: "Carpinteros de armar y de obra blanca"},
{codigo: "7119", ocupacion: "Oficiales y operarios de la construcción (obra gruesa) y afines no clasificados bajo otros epígrafes"},
{codigo: "7121", ocupacion: "Techadores"},
{codigo: "7122", ocupacion: "Parqueteros y colocadores de suelos"},
{codigo: "7123", ocupacion: "Revocadores"},
{codigo: "7124", ocupacion: "Instaladores de material aislante y de insonorización"},
{codigo: "7125", ocupacion: "Cristaleros"},
{codigo: "7126", ocupacion: "Fontaneros e instaladores de tuberías"},
{codigo: "7127", ocupacion: "Mecánicos-montadores de instalaciones de refrigeración y climatización"},
{codigo: "7131", ocupacion: "Pintores y empapeladores"},
{codigo: "7132", ocupacion: "Barnizadores y afines"},
{codigo: "7133", ocupacion: "Limpiadores de fachadas y deshollinadores"},
{codigo: "7211", ocupacion: "Moldeadores y macheros"},
{codigo: "7212", ocupacion: "Soldadores y oxicortadores"},
{codigo: "7213", ocupacion: "Chapistas y caldereros"},
{codigo: "7214", ocupacion: "Montadores de estructuras metálicas"},
{codigo: "7215", ocupacion: "Aparejadores y empalmadores de cables"},
{codigo: "7221", ocupacion: "Herreros y forjadores"},
{codigo: "7222", ocupacion: "Herramentistas y afines"},
{codigo: "7223", ocupacion: "Reguladores y operadores de máquinas herramientas"},
{codigo: "7224", ocupacion: "Pulidores de metales y afiladores de herramientas"},
{codigo: "7231", ocupacion: "Mecánicos y reparadores de vehículos de motor"},
{codigo: "7232", ocupacion: "Mecánicos y reparadores de motores de avión"},
{codigo: "7233", ocupacion: "Mecánicos y reparadores de máquinas agrícolas e industriales"},
{codigo: "7234", ocupacion: "Reparadores de bicicletas y afines"},
{codigo: "7311", ocupacion: "Mecánicos y reparadores de instrumentos de precisión"},
{codigo: "7312", ocupacion: "Fabricantes y afinadores de instrumentos musicales"},
{codigo: "7313", ocupacion: "Joyeros, orfebres y plateros"},
{codigo: "7314", ocupacion: "Alfareros y afines (barro, arcilla y abrasivos)"},
{codigo: "7315", ocupacion: "Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio"},
{codigo: "7316", ocupacion: "Redactores de carteles, pintores decorativos y grabadores"},
{codigo: "7317", ocupacion: "Artesanos en madera, cestería y materiales similares"},
{codigo: "7318", ocupacion: "Artesanos de los tejidos, el cuero y materiales similares"},
{codigo: "7319", ocupacion: "Artesanos no clasificados bajo otros epígrafes"},
{codigo: "7321", ocupacion: "Cajistas, tipógrafos y afines"},
{codigo: "7322", ocupacion: "Impresores"},
{codigo: "7323", ocupacion: "Encuadernadores y afines"},
{codigo: "7411", ocupacion: "Electricistas de obras y afines"},
{codigo: "7412", ocupacion: "Mecánicos y ajustadores electricistas"},
{codigo: "7413", ocupacion: "Instaladores y reparadores de líneas eléctricas "},
{codigo: "7421", ocupacion: "Mecánicos y reparadores en electrónica"},
{codigo: "7422", ocupacion: "Instaladores y reparadores en tecnología de la información y las comunicaciones"},
{codigo: "7511", ocupacion: "Carniceros, pescaderos y afines"},
{codigo: "7512", ocupacion: "Panaderos, pasteleros y confiteros"},
{codigo: "7513", ocupacion: "Operarios de la elaboración de productos lácteos"},
{codigo: "7514", ocupacion: "Operarios de la conservación de frutas, legumbres, verduras y afines"},
{codigo: "7515", ocupacion: "Catadores y clasificadores de alimentos y bebidas"},
{codigo: "7516", ocupacion: "Preparadores y elaboradores de tabaco y sus productos"},
{codigo: "7521", ocupacion: "Operarios del tratamiento de la madera"},
{codigo: "7522", ocupacion: "Ebanistas y afines"},
{codigo: "7523", ocupacion: "Reguladores y operadores de máquinas de labrar madera"},
{codigo: "7531", ocupacion: "Sastres, modistos, peleteros y sombrereros"},
{codigo: "7532", ocupacion: "Patronistas y cortadores de tela y afines"},
{codigo: "7533", ocupacion: "Costureros, bordadores y afines"},
{codigo: "7534", ocupacion: "Tapiceros, colchoneros y afines"},
{codigo: "7535", ocupacion: "Apelambradores, pellejeros y curtidores"},
{codigo: "7536", ocupacion: "Zapateros y afines"},
{codigo: "7541", ocupacion: "Buzos"},
{codigo: "7542", ocupacion: "Dinamiteros y pegadores"},
{codigo: "7543", ocupacion: "Clasificadores y probadores de productos (excluyendo alimentos y bebidas)"},
{codigo: "7544", ocupacion: "Fumigadores y otros controladores de plagas y malas hierbas"},
{codigo: "7549", ocupacion: "Oficiales, operarios y artesanos de artes mecánicas y de otros oficios no clasificados bajo otros epígrafes"},
{codigo: "8111", ocupacion: "Mineros y operadores de instalaciones mineras"},
{codigo: "8112", ocupacion: "Operadores de instalaciones de procesamiento de minerales y rocas"},
{codigo: "8113", ocupacion: "Perforadores y sondistas de pozos y afines"},
{codigo: "8114", ocupacion: "Operadores de máquinas para fabricar cemento y otros productos minerales"},
{codigo: "8121", ocupacion: "Operadores de instalaciones de procesamiento de metales"},
{codigo: "8122", ocupacion: "Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales "},
{codigo: "8131", ocupacion: "Operadores de plantas y máquinas de productos químicos"},
{codigo: "8132", ocupacion: "Operadores de máquinas para fabricar productos fotográficos"},
{codigo: "8141", ocupacion: "Operadores de máquinas para fabricar productos de caucho"},
{codigo: "8142", ocupacion: "Operadores de máquinas para fabricar productos de material plástico"},
{codigo: "8143", ocupacion: "Operadores de máquinas para fabricar productos de papel"},
{codigo: "8151", ocupacion: "Operadores de máquinas de preparación de fibras, hilado y devanado"},
{codigo: "8152", ocupacion: "Operadores de telares y otras máquinas tejedoras"},
{codigo: "8153", ocupacion: "Operadores de máquinas de coser"},
{codigo: "8154", ocupacion: "Operadores de máquinas de blanqueamiento, teñido y limpieza de tejidos"},
{codigo: "8155", ocupacion: "Operadores de máquinas de tratamiento de pieles y cueros"},
{codigo: "8156", ocupacion: "Operadores de máquinas para la fabricación de calzado y afines"},
{codigo: "8157", ocupacion: "Operadores de máquinas lavarropas"},
{codigo: "8159", ocupacion: "Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero no clasificados bajo otros epígrafes"},
{codigo: "8160", ocupacion: "Operadores de máquinas para elaborar alimentos y productos afines"},
{codigo: "8171", ocupacion: "Operadores de instalaciones para la preparación de pasta para papel y papel"},
{codigo: "8172", ocupacion: "Operadores de instalaciones de procesamiento de la madera"},
{codigo: "8181", ocupacion: "Operadores de instalaciones de vidriería y cerámica"},
{codigo: "8182", ocupacion: "Operadores de máquinas de vapor y calderas"},
{codigo: "8183", ocupacion: "Operadores de máquinas de embalaje, embotellamiento y etiquetado "},
{codigo: "8189", ocupacion: "Operadores de máquinas y de instalaciones fijas no clasificados bajo otros epígrafes"},
{codigo: "8211", ocupacion: "Ensambladores de maquinaria mecánica"},
{codigo: "8212", ocupacion: "Ensambladores de equipos eléctricos y electrónicos"},
{codigo: "8219", ocupacion: "Ensambladores no clasificados bajo otros epígrafes"},
{codigo: "8311", ocupacion: "Maquinistas de locomotoras"},
{codigo: "8312", ocupacion: "Guardafrenos, guardagujas y agentes de maniobras"},
{codigo: "8321", ocupacion: "Conductores de motocicletas"},
{codigo: "8322", ocupacion: "Conductores de automóviles, taxis y camionetas"},
{codigo: "8331", ocupacion: "Conductores de autobuses y tranvías"},
{codigo: "8332", ocupacion: "Conductores de camiones pesados"},
{codigo: "8341", ocupacion: "Operadores de maquinaria agrícola y forestal móvil"},
{codigo: "8342", ocupacion: "Operadores de máquinas de movimiento de tierras y afines"},
{codigo: "8343", ocupacion: "Operadores de grúas, aparatos elevadores y afines"},
{codigo: "8344", ocupacion: "Operadores de autoelevadoras"},
{codigo: "8350", ocupacion: "Marineros de cubierta y afines"},
{codigo: "9111", ocupacion: "Limpiadores y asistentes domésticos"},
{codigo: "9112", ocupacion: "Limpiadores y asistentes de oficinas, hoteles y otros establecimientos"},
{codigo: "9121", ocupacion: "Lavanderos y planchadores manuales"},
{codigo: "9122", ocupacion: "Lavadores de vehículos"},
{codigo: "9123", ocupacion: "Lavadores de ventanas"},
{codigo: "9129", ocupacion: "Otro personal de limpieza"},
{codigo: "9211", ocupacion: "Peones de explotaciones agrícolas"},
{codigo: "9212", ocupacion: "Peones de explotaciones ganaderas"},
{codigo: "9213", ocupacion: "Peones de explotaciones de cultivos mixtos y ganaderos"},
{codigo: "9214", ocupacion: "Peones de jardinería y horticultura"},
{codigo: "9215", ocupacion: "Peones forestales"},
{codigo: "9216", ocupacion: "Peones de pesca y acuicultura"},
{codigo: "9311", ocupacion: "Peones de minas y canteras"},
{codigo: "9312", ocupacion: "Peones de obras públicas y mantenimiento"},
{codigo: "9313", ocupacion: "Peones de la construcción de edificios"},
{codigo: "9321", ocupacion: "Empacadores manuales"},
{codigo: "9329", ocupacion: "Peones de la industria manufacturera no clasificados bajo otros epígrafes"},
{codigo: "9331", ocupacion: "Conductores de vehículos accionados a pedal o a brazo"},
{codigo: "9332", ocupacion: "Conductores de vehículos y máquinas de tracción animal"},
{codigo: "9333", ocupacion: "Peones de carga"},
{codigo: "9334", ocupacion: "Reponedores de estanterías"},
{codigo: "9411", ocupacion: "Cocineros de comidas rápidas"},
{codigo: "9412", ocupacion: "Ayudantes de cocina"},
{codigo: "9510", ocupacion: "Trabajadores ambulantes de servicios y afines"},
{codigo: "9520", ocupacion: "Vendedores ambulantes (excluyendo de comida)"},
{codigo: "9611", ocupacion: "Recolectores de basura y material reciclable"},
{codigo: "9612", ocupacion: "Clasificadores de desechos"},
{codigo: "9613", ocupacion: "Barrenderos y afines"},
{codigo: "9621", ocupacion: "Mensajeros, mandaderos, maleteros y repartidores"},
{codigo: "9622", ocupacion: "Personas que realizan trabajos varios"},
{codigo: "9623", ocupacion: "Recolectores de dinero en aparatos de venta automática y lectores de medidores"},
{codigo: "9624", ocupacion: "Acarreadores de agua y recolectores  de  leña"}]

export { ocupaciones }
