const paises = [{ codigo: "AF", pais: "Afganistán" },
{ codigo: "AL", pais: "Albania" },
{ codigo: "DE", pais: "Alemania" },
{ codigo: "AD", pais: "Andorra" },
{ codigo: "AO", pais: "Angola" },
{ codigo: "AI", pais: "Anguila" },
{ codigo: "AQ", pais: "Antártida" },
{ codigo: "AG", pais: "Antigua y Barbuda" },
{ codigo: "SA", pais: "Arabia Saudí" },
{ codigo: "DZ", pais: "Argelia" },
{ codigo: "AR", pais: "Argentina" },
{ codigo: "AM", pais: "Armenia" },
{ codigo: "AW", pais: "Aruba" },
{ codigo: "AU", pais: "Australia" },
{ codigo: "AT", pais: "Austria" },
{ codigo: "AZ", pais: "Azerbaiyán" },
{ codigo: "BS", pais: "Bahamas" },
{ codigo: "BD", pais: "Bangladés" },
{ codigo: "BB", pais: "Barbados" },
{ codigo: "BH", pais: "Baréin" },
{ codigo: "BE", pais: "Bélgica" },
{ codigo: "BZ", pais: "Belice" },
{ codigo: "BJ", pais: "Benín" },
{ codigo: "BM", pais: "Bermudas" },
{ codigo: "BY", pais: "Bielorrusia" },
{ codigo: "BO", pais: "Bolivia" },
{ codigo: "BA", pais: "Bosnia-Herzegovina" },
{ codigo: "BW", pais: "Botsuana" },
{ codigo: "BR", pais: "Brasil" },
{ codigo: "BN", pais: "Brunéi" },
{ codigo: "BG", pais: "Bulgaria" },
{ codigo: "BF", pais: "Burkina Faso" },
{ codigo: "BI", pais: "Burundi" },
{ codigo: "BT", pais: "Bután" },
{ codigo: "CV", pais: "Cabo Verde" },
{ codigo: "KH", pais: "Camboya" },
{ codigo: "CM", pais: "Camerún" },
{ codigo: "CA", pais: "Canadá" },
{ codigo: "BQ", pais: "Caribe neerlandés" },
{ codigo: "QA", pais: "Catar" },
{ codigo: "EA", pais: "Ceuta y Melilla" },
{ codigo: "TD", pais: "Chad" },
{ codigo: "CL", pais: "Chile" },
{ codigo: "CN", pais: "China" },
{ codigo: "CY", pais: "Chipre" },
{ codigo: "VA", pais: "Ciudad del Vaticano" },
{ codigo: "CO", pais: "Colombia" },
{ codigo: "KM", pais: "Comoras" },
{ codigo: "KP", pais: "Corea del Norte" },
{ codigo: "KR", pais: "Corea del Sur" },
{ codigo: "CI", pais: "Costa de Marfil" },
{ codigo: "CR", pais: "Costa Rica" },
{ codigo: "HR", pais: "Croacia" },
{ codigo: "CU", pais: "Cuba" },
{ codigo: "CW", pais: "Curazao" },
{ codigo: "DG", pais: "Diego García" },
{ codigo: "DK", pais: "Dinamarca" },
{ codigo: "DM", pais: "Dominica" },
{ codigo: "EC", pais: "Ecuador" },
{ codigo: "EG", pais: "Egipto" },
{ codigo: "SV", pais: "El Salvador" },
{ codigo: "AE", pais: "Emiratos Árabes Unidos" },
{ codigo: "ER", pais: "Eritrea" },
{ codigo: "SK", pais: "Eslovaquia" },
{ codigo: "SI", pais: "Eslovenia" },
{ codigo: "ES", pais: "España" },
{ codigo: "US", pais: "Estados Unidos" },
{ codigo: "EE", pais: "Estonia" },
{ codigo: "ET", pais: "Etiopía" },
{ codigo: "PH", pais: "Filipinas" },
{ codigo: "FI", pais: "Finlandia" },
{ codigo: "FJ", pais: "Fiyi" },
{ codigo: "FR", pais: "Francia" },
{ codigo: "GA", pais: "Gabón" },
{ codigo: "GM", pais: "Gambia" },
{ codigo: "GE", pais: "Georgia" },
{ codigo: "GH", pais: "Ghana" },
{ codigo: "GI", pais: "Gibraltar" },
{ codigo: "GD", pais: "Granada" },
{ codigo: "GR", pais: "Grecia" },
{ codigo: "GL", pais: "Groenlandia" },
{ codigo: "GP", pais: "Guadalupe" },
{ codigo: "GU", pais: "Guam" },
{ codigo: "GT", pais: "Guatemala" },
{ codigo: "GF", pais: "Guayana Francesa" },
{ codigo: "GG", pais: "Guernesey" },
{ codigo: "GN", pais: "Guinea" },
{ codigo: "GQ", pais: "Guinea Ecuatorial" },
{ codigo: "GW", pais: "Guinea-Bisáu" },
{ codigo: "GY", pais: "Guyana" },
{ codigo: "HT", pais: "Haití" },
{ codigo: "HN", pais: "Honduras" },
{ codigo: "HU", pais: "Hungría" },
{ codigo: "IN", pais: "India" },
{ codigo: "ID", pais: "Indonesia" },
{ codigo: "IR", pais: "Irán" },
{ codigo: "IQ", pais: "Iraq" },
{ codigo: "IE", pais: "Irlanda" },
{ codigo: "CX", pais: "Isla Christmas" },
{ codigo: "AC", pais: "Isla de la Ascensión" },
{ codigo: "IM", pais: "Isla de Man" },
{ codigo: "NU", pais: "Isla Niue" },
{ codigo: "NF", pais: "Isla Norfolk" },
{ codigo: "IS", pais: "Islandia" },
{ codigo: "AX", pais: "Islas Åland" },
{ codigo: "KY", pais: "Islas Caimán" },
{ codigo: "IC", pais: "islas Canarias" },
{ codigo: "CC", pais: "Islas Cocos" },
{ codigo: "CK", pais: "Islas Cook" },
{ codigo: "FO", pais: "Islas Feroe" },
{ codigo: "GS", pais: "Islas Georgia del Sur y Sandwich del Sur" },
{ codigo: "FK", pais: "Islas Malvinas" },
{ codigo: "MP", pais: "Islas Marianas del Norte" },
{ codigo: "MH", pais: "Islas Marshall" },
{ codigo: "UM", pais: "Islas menores alejadas de EE. UU." },
{ codigo: "PN", pais: "Islas Pitcairn" },
{ codigo: "SB", pais: "Islas Salomón" },
{ codigo: "TC", pais: "Islas Turcas y Caicos" },
{ codigo: "VG", pais: "Islas Vírgenes Británicas" },
{ codigo: "VI", pais: "Islas Vírgenes de EE. UU." },
{ codigo: "IL", pais: "Israel" },
{ codigo: "IT", pais: "Italia" },
{ codigo: "JM", pais: "Jamaica" },
{ codigo: "JP", pais: "Japón" },
{ codigo: "JE", pais: "Jersey" },
{ codigo: "JO", pais: "Jordania" },
{ codigo: "KZ", pais: "Kazajistán" },
{ codigo: "KE", pais: "Kenia" },
{ codigo: "KG", pais: "Kirguistán" },
{ codigo: "KI", pais: "Kiribati" },
{ codigo: "XK", pais: "Kosovo" },
{ codigo: "KW", pais: "Kuwait" },
{ codigo: "LA", pais: "Laos" },
{ codigo: "LS", pais: "Lesoto" },
{ codigo: "LV", pais: "Letonia" },
{ codigo: "LB", pais: "Líbano" },
{ codigo: "LR", pais: "Liberia" },
{ codigo: "LY", pais: "Libia" },
{ codigo: "LI", pais: "Liechtenstein" },
{ codigo: "LT", pais: "Lituania" },
{ codigo: "LU", pais: "Luxemburgo" },
{ codigo: "MK", pais: "Macedonia" },
{ codigo: "MG", pais: "Madagascar" },
{ codigo: "MY", pais: "Malasia" },
{ codigo: "MW", pais: "Malaui" },
{ codigo: "MV", pais: "Maldivas" },
{ codigo: "ML", pais: "Mali" },
{ codigo: "MT", pais: "Malta" },
{ codigo: "MA", pais: "Marruecos" },
{ codigo: "MQ", pais: "Martinica" },
{ codigo: "MU", pais: "Mauricio" },
{ codigo: "MR", pais: "Mauritania" },
{ codigo: "YT", pais: "Mayotte" },
{ codigo: "MX", pais: "México" },
{ codigo: "FM", pais: "Micronesia" },
{ codigo: "MD", pais: "Moldavia" },
{ codigo: "MC", pais: "Mónaco" },
{ codigo: "MN", pais: "Mongolia" },
{ codigo: "ME", pais: "Montenegro" },
{ codigo: "MS", pais: "Montserrat" },
{ codigo: "MZ", pais: "Mozambique" },
{ codigo: "MM", pais: "Myanmar (Birmania)" },
{ codigo: "NA", pais: "Namibia" },
{ codigo: "NR", pais: "Nauru" },
{ codigo: "NP", pais: "Nepal" },
{ codigo: "NI", pais: "Nicaragua" },
{ codigo: "NE", pais: "Níger" },
{ codigo: "NG", pais: "Nigeria" },
{ codigo: "NO", pais: "Noruega" },
{ codigo: "NC", pais: "Nueva Caledonia" },
{ codigo: "NZ", pais: "Nueva Zelanda" },
{ codigo: "OM", pais: "Omán" },
{ codigo: "NL", pais: "Países Bajos" },
{ codigo: "PK", pais: "Pakistán" },
{ codigo: "PW", pais: "Palau" },
{ codigo: "PA", pais: "Panamá" },
{ codigo: "PG", pais: "Papúa Nueva Guinea" },
{ codigo: "PY", pais: "Paraguay" },
{ codigo: "PE", pais: "Perú" },
{ codigo: "PF", pais: "Polinesia Francesa" },
{ codigo: "PL", pais: "Polonia" },
{ codigo: "PT", pais: "Portugal" },
{ codigo: "PR", pais: "Puerto Rico" },
{ codigo: "HK", pais: "RAE de Hong Kong (China)" },
{ codigo: "MO", pais: "RAE de Macao (China)" },
{ codigo: "GB", pais: "Reino Unido" },
{ codigo: "CF", pais: "República Centroafricana" },
{ codigo: "CZ", pais: "República Checa" },
{ codigo: "CG", pais: "República del Congo" },
{ codigo: "CD", pais: "República Democrática del Congo" },
{ codigo: "DO", pais: "República Dominicana" },
{ codigo: "RE", pais: "Reunión" },
{ codigo: "RW", pais: "Ruanda" },
{ codigo: "RO", pais: "Rumanía" },
{ codigo: "RU", pais: "Rusia" },
{ codigo: "EH", pais: "Sáhara Occidental" },
{ codigo: "WS", pais: "Samoa" },
{ codigo: "AS", pais: "Samoa Americana" },
{ codigo: "BL", pais: "San Bartolomé" },
{ codigo: "KN", pais: "San Cristóbal y Nieves" },
{ codigo: "SM", pais: "San Marino" },
{ codigo: "MF", pais: "San Martín" },
{ codigo: "PM", pais: "San Pedro y Miquelón" },
{ codigo: "VC", pais: "San Vicente y las Granadinas" },
{ codigo: "SH", pais: "Santa Elena" },
{ codigo: "LC", pais: "Santa Lucía" },
{ codigo: "ST", pais: "Santo Tomé y Príncipe" },
{ codigo: "SN", pais: "Senegal" },
{ codigo: "RS", pais: "Serbia" },
{ codigo: "SC", pais: "Seychelles" },
{ codigo: "SL", pais: "Sierra Leona" },
{ codigo: "SG", pais: "Singapur" },
{ codigo: "SX", pais: "Sint Maarten" },
{ codigo: "SY", pais: "Siria" },
{ codigo: "SO", pais: "Somalia" },
{ codigo: "LK", pais: "Sri Lanka" },
{ codigo: "SZ", pais: "Suazilandia" },
{ codigo: "ZA", pais: "Sudáfrica" },
{ codigo: "SD", pais: "Sudán" },
{ codigo: "SS", pais: "Sudán del Sur" },
{ codigo: "SE", pais: "Suecia" },
{ codigo: "CH", pais: "Suiza" },
{ codigo: "SR", pais: "Surinam" },
{ codigo: "SJ", pais: "Svalbard y Jan Mayen" },
{ codigo: "TH", pais: "Tailandia" },
{ codigo: "TW", pais: "Taiwán" },
{ codigo: "TZ", pais: "Tanzania" },
{ codigo: "TJ", pais: "Tayikistán" },
{ codigo: "IO", pais: "Territorio Británico del Océano Índico" },
{ codigo: "TF", pais: "Territorios Australes Franceses" },
{ codigo: "PS", pais: "Territorios Palestinos" },
{ codigo: "TL", pais: "Timor Oriental" },
{ codigo: "TG", pais: "Togo" },
{ codigo: "TK", pais: "Tokelau" },
{ codigo: "TO", pais: "Tonga" },
{ codigo: "TT", pais: "Trinidad y Tobago" },
{ codigo: "TA", pais: "Tristán da Cunha" },
{ codigo: "TN", pais: "Túnez" },
{ codigo: "TM", pais: "Turkmenistán" },
{ codigo: "TR", pais: "Turquía" },
{ codigo: "TV", pais: "Tuvalu" },
{ codigo: "UA", pais: "Ucrania" },
{ codigo: "UG", pais: "Uganda" },
{ codigo: "UY", pais: "Uruguay" },
{ codigo: "UZ", pais: "Uzbekistán" },
{ codigo: "VU", pais: "Vanuatu" },
{ codigo: "VE", pais: "Venezuela" },
{ codigo: "VN", pais: "Vietnam" },
{ codigo: "WF", pais: "Wallis y Futuna" },
{ codigo: "YE", pais: "Yemen" },
{ codigo: "DJ", pais: "Yibuti" },
{ codigo: "ZM", pais: "Zambia" },
{ codigo: "ZW", pais: "Zimbabue" }]

export { paises }
